name: teads_sdk_flutter
description: Teads allows you to integrate a single SDK into your app, and serve premium branded ads from Teads SSP.
version: 0.0.1
homepage: https://github.com/teads/TeadsSDK-flutter

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: tv.teads.teadssdkflutter.teads_sdk_flutter
        pluginClass: TeadsSdkFlutterPlugin
      ios:
        pluginClass: TeadsSdkFlutterPlugin