name: teads_admob_adapter
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  google_mobile_ads: ^2.0.1
  teads_sdk_flutter:
    path: ../TeadsSDK

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: tv.teads.teadsadmobadapter.teads_admob_adapter
        pluginClass: TeadsAdmobAdapterPlugin
      ios:
        pluginClass: TeadsAdmobAdapterPlugin